---
swagger: "2.0"
info:
  description: This is GamUS Four's api
  version: 2.0.0
  title: GamUS Four API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: gamus-four.appspot.com
basePath: /api
schemes:
- https
paths:
  /games:
    get:
      tags:
      - general
      summary: Get all games information
      operationId: getGame
      parameters: []
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Game'
        400:
          description: bad input parameter
    post:
      tags:
      - general
      summary: Post a game to repository
      operationId: addGame
      parameters: []
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Game'
        400:
          description: bad input parameter
    put:
      tags:
      - general
      summary: Update a game from repository
      operationId: updateGame
      parameters: []
      responses:
        204:
          description: No Content
        400:
          description: bad input parameter
  /games/{id}:
    get:
      tags:
      - id
      summary: Get a information's game by a id
      operationId: getGameId
      parameters:
      - name: id
        in: path
        description: ID of the game
        required: true
        type: integer
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Game'
        400:
          description: bad input parameter
    delete:
      tags:
      - id
      summary: Delete a game with a id from repository
      operationId: deleteGame
      parameters:
      - name: id
        in: path
        description: ID of the game
        required: true
        type: integer
      responses:
        204:
          description: No Content
        400:
          description: bad input parameter
  /games/{genres}&{name}:
    get:
      tags:
      - genres
      summary: Get three random game's genres by a name
      operationId: getGameGenre
      parameters:
      - name: name
        in: path
        description: Name of the game
        required: true
        type: string
      - name: genres
        in: path
        description: Genres of the game
        required: true
        type: array
        items:
          type: integer
        collectionFormat: csv
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Genre'
        400:
          description: bad input parameter
definitions:
  Game:
    type: object
    required:
    - cover
    - esrb
    - genres
    - id
    - name
    - pegi
    - platforms
    - rating
    - summary
    properties:
      id:
        type: integer
        example: 12345
      name:
        type: string
        example: Super Mario
      summary:
        type: string
        example: Uncover all the mysteries of Dracula’s castle.
      genres:
        type: array
        example:
        - 12
        - 34
        items:
          type: integer
      cover:
        $ref: '#/definitions/Cover'
      rating:
        type: number
        example: 89.1307615539013
      platforms:
        type: array
        example:
        - 40
        - 45
        items:
          type: integer
      esrb:
        $ref: '#/definitions/Esrb'
      pegi:
        $ref: '#/definitions/Pegi'
    example:
      summary: Uncover all the mysteries of Dracula’s castle.
      cover:
        width: 795
        cloudinary_id: scutr4p9gytl4txb2soy
        url: //images.igdb.com/igdb/image/upload/t_thumb/scutr4p9gytl4txb2soy.jpg
        height: 554
      esrb:
        rating: 5
        synopsis: This is an adventure role-playing game in which players assume the role of a man helping a half-human child defeat an evil force to become king. From a third-person perspective, players explore environments and engage in melee combat against fantasy creatures (e.g., half-human soldiers, skeletons, monsters). Characters use swords, fireballs, pistols, and arrows to defeat enemies. Combat is highlighted by impact sounds, cries of pain, and occasional gunfire. A handful of cutscenes depict quick splashes of blood when characters are shot.
      pegi:
        rating: 3
        synopsis: This game has been rated PEGI 12 for depictions of realistic looking violence towards a fantasy character, and depictions of non-realistic looking violence towards human-like characters. Not suitable for persons under 12 years of age.
      genres:
      - 12
      - 34
      name: Super Mario
      rating: 89.1307615539013
      id: 12345
      platforms:
      - 40
      - 45
  Cover:
    type: object
    required:
    - cloudinary_id
    - height
    - url
    - width
    properties:
      url:
        type: string
        example: //images.igdb.com/igdb/image/upload/t_thumb/scutr4p9gytl4txb2soy.jpg
      cloudinary_id:
        type: string
        example: scutr4p9gytl4txb2soy
      width:
        type: integer
        example: 795
      height:
        type: integer
        example: 554
    example:
      width: 795
      cloudinary_id: scutr4p9gytl4txb2soy
      url: //images.igdb.com/igdb/image/upload/t_thumb/scutr4p9gytl4txb2soy.jpg
      height: 554
  Esrb:
    type: object
    required:
    - rating
    - synopsis
    properties:
      synopsis:
        type: string
        example: This is an adventure role-playing game in which players assume the role of a man helping a half-human child defeat an evil force to become king. From a third-person perspective, players explore environments and engage in melee combat against fantasy creatures (e.g., half-human soldiers, skeletons, monsters). Characters use swords, fireballs, pistols, and arrows to defeat enemies. Combat is highlighted by impact sounds, cries of pain, and occasional gunfire. A handful of cutscenes depict quick splashes of blood when characters are shot.
      rating:
        type: integer
        example: 5
    example:
      rating: 5
      synopsis: This is an adventure role-playing game in which players assume the role of a man helping a half-human child defeat an evil force to become king. From a third-person perspective, players explore environments and engage in melee combat against fantasy creatures (e.g., half-human soldiers, skeletons, monsters). Characters use swords, fireballs, pistols, and arrows to defeat enemies. Combat is highlighted by impact sounds, cries of pain, and occasional gunfire. A handful of cutscenes depict quick splashes of blood when characters are shot.
  Genre:
    type: object
    required:
    - games
    - id
    properties:
      id:
        type: integer
        example: 8
      games:
        type: integer
        example: 16314
    example:
      games: 16314
      id: 8
  Pegi:
    type: object
    required:
    - rating
    - synopsis
    properties:
      synopsis:
        type: string
        example: This game has been rated PEGI 12 for depictions of realistic looking violence towards a fantasy character, and depictions of non-realistic looking violence towards human-like characters. Not suitable for persons under 12 years of age.
      rating:
        type: integer
        example: 3
    example:
      rating: 3
      synopsis: This game has been rated PEGI 12 for depictions of realistic looking violence towards a fantasy character, and depictions of non-realistic looking violence towards human-like characters. Not suitable for persons under 12 years of age.
